openapi: "3.0.3"
info:
  title: "jobservice API"
  description: "jobservice API"
  version: "1.0.0"
servers:
  - url: "https://jobservice"
paths:
  /api/jobs:
    post:
      summary: "POST api/jobs"
      operationId: "createJob"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Job"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
    get:
      summary: "GET api/jobs"
      operationId: "getJobs"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
  /api/jobs/{id}/apply:
    post:
      summary: "POST api/jobs/{id}/apply"
      operationId: "applyForJob"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationDTO"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
  /api/jobs/{id}:
    get:
      summary: "GET api/jobs/{id}"
      operationId: "getJob"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
    put:
      summary: "PUT api/jobs/{id}"
      operationId: "updateJob"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Job"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
    delete:
      summary: "DELETE api/jobs/{id}"
      operationId: "deleteJob"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
  /api/jobs/{id}/applications:
    get:
      summary: "GET api/jobs/{id}/applications"
      operationId: "getJobApplications"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
  /api/jobs/companies/{id}:
    get:
      summary: "GET api/jobs/companies/{id}"
      operationId: "getJobsByCompanyId"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ResponseEntity"
components:
  schemas:
    Application:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        userId:
          type: "string"
        status:
          type: "string"
          enum:
            - "PENDING"
            - "ACCEPTED"
            - "REJECTED"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
        job:
          $ref: "#/components/schemas/Job"
    Job:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        title:
          type: "string"
        location:
          type: "string"
        description:
          type: "string"
        jobType:
          type: "string"
          enum:
            - "FRONTEND"
            - "BACKEND"
            - "FULLSTACK"
            - "ARCHITECT"
            - "DEVOPS"
            - "QA"
            - "MANAGER"
            - "OTHER"
        companyId:
          type: "integer"
          format: "int64"
        salary:
          type: "number"
          format: "double"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
        expiresAt:
          type: "string"
          format: "date-time"
        applications:
          type: "array"
          items:
            $ref: "#/components/schemas/Application"
    HttpHeaders:
      type: "object"
      properties: { }
    ResponseEntity:
      type: "object"
      properties:
        headers:
          $ref: "#/components/schemas/HttpHeaders"
    ApplicationDTO:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        userId:
          type: "string"
        status:
          type: "string"
          enum:
            - "PENDING"
            - "ACCEPTED"
            - "REJECTED"
        createdAt:
          type: "string"
          format: "date-time"
        updatedAt:
          type: "string"
          format: "date-time"
        jobId:
          type: "integer"
          format: "int64"