apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config-job
data:
  init.sql: |
    ALTER USER postgres PASSWORD 'password';
    CREATE TABLE jobs
    (
        id          SERIAL PRIMARY KEY,
        title       VARCHAR(255)   NOT NULL,
        description TEXT           NOT NULL,
        company_id  INTEGER        NOT NULL,
        location    VARCHAR(255)   NOT NULL,
        salary      DECIMAL(10, 2) NOT NULL,
        job_type    VARCHAR(10)    NOT NULL,
        created_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        expires_at  TIMESTAMP      NOT NULL
    );

    CREATE TABLE applications
    (
        id          SERIAL PRIMARY KEY,
        status      VARCHAR(10)    NOT NULL,
        job_id      INTEGER        NOT NULL REFERENCES jobs (id),
        user_id     VARCHAR(50)    NOT NULL,
        application_text VARCHAR(255)   NOT NULL,
        created_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        UNIQUE (job_id, user_id)
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: nicolajh/swj-job
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: databasesecrets
                  key: connection-string-job-service
            - name: POSTGRES_DB
              value: database-job-service
            - name: POSTGRES_HOST
              value: postgres
            - name: SPRING_JMS_SERVICEBUS_CONNECTION-STRING
              valueFrom:
                secretKeyRef:
                  name: mqsecret
                  key: connection-string
            - name: SPRING_JMS_SERVICEBUS_PRICING-TIER
              value: standard
          resources:
            limits:  
              cpu: "250m"
              memory: "500Mi"
            requests:  
              cpu: "250m"
              memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-job
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: job-service
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80