apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-config
data:
  init.sql: |
    ALTER USER postgres PASSWORD 'password';
    CREATE TABLE jobs
    (
        id          SERIAL PRIMARY KEY,
        title       VARCHAR(255)   NOT NULL,
        description TEXT           NOT NULL,
        company_id  INTEGER        NOT NULL,
        location    VARCHAR(255)   NOT NULL,
        salary      DECIMAL(10, 2) NOT NULL,
        job_type    VARCHAR(10)    NOT NULL,
        created_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        expires_at  TIMESTAMP      NOT NULL
    );

    CREATE TABLE applications
    (
        id          SERIAL PRIMARY KEY,
        status      VARCHAR(10)    NOT NULL,
        job_id      INTEGER        NOT NULL REFERENCES jobs (id),
        user_id     INTEGER        NOT NULL,
        created_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        updated_at  TIMESTAMP      NOT NULL DEFAULT NOW(),
        UNIQUE (job_id, user_id)
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: nicolajh/job-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://database-job-service:5432/postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-job-service
  template:
    metadata:
      labels:
        app: database-job-service
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          volumeMounts:
            - name: postgresql-initdb
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: postgres
          ports:
            - containerPort: 5432
      volumes:
        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: database-job-service
spec:
  selector:
    app: database-job-service
  ports:
    - name: http
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
