#SPRING CONFIGURATION
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: java
    password: java
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

mq:
  topic: new_job

#LOGGING CONFIGURATION
logging:
  level:
    org:
      hibernate:
        sql: info