name: job-service-azure

on:
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  ACR_RESOURCE_GROUP: job-boards-rg
  CLUSTER_NAME: job-boards-aks
  CLUSTER_RESOURCE_GROUP: job-boards-rg
  DEPLOYMENT_MANIFEST_PATH: ./deployment.yaml
jobs:
  buildTestAndUploadImage:
    uses: ./.github/workflows/pr-workflow.yml
    secrets:
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs:
      - buildTestAndUploadImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1.4.3
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/use-kubelogin@v1
        name: Set up kubelogin for non-interactive login
        with:
          kubelogin-version: v0.0.25
      - uses: azure/aks-set-context@v3
        name: Get K8s context
        with:
          admin: "false"
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          use-kubelogin: "true"
      - uses: Azure/k8s-deploy@v4
        name: Deploys application
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          namespace: default
